### ISSUE TITLE
error multiple clients simultaneos diferent stream

### ISSUE THREAD

**Issue by akuaman** [marquezpsergio/acestream-docker-home#3]
HI, with one client all ist ok, but when connect more cients and diferent stream, the playback stop.

**Comment by marquezpsergio** [comment]
Other users have also experienced the same problem and I have not been able to investigate why it happens. I think it may be caused by the port being used or the Acestream motor itself.

If you can solve it, it would be a pleasure to comment and fix it!

Thanks for your comment. All the best!

**Comment by juhacz** [comment]
This is limitation of acestream, create multiple instances of docker containers with acestream, with different ports.

**Comment by akuaman** [comment]
Thanks for the replay, I use multiple docker for acestreamproxy in
conjunction with this m3u-stream-merger-proxy

**Comment by juhacz** [comment]
@sergiomarquezdev It's great that you've managed to overcome the limitations that caused only one stream to be viewed on one Docker instance. There's one more limitation, you can't view the same stream on two devices at the same time, is it possible to do that?
